post http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Maunon toinen kävelylenkki",
    "author": "Karo ja Ville",
    "url": "www.mel.fi",
    "likes": 10,
    "userId": "5d9cb3ed4ad59e0b044aca5a"
}